<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="dnlib">
      <HintPath>../../../repos/hybridclr_unity/Plugins/dnlib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
