<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>HybridCLR.ReferenceRunner</AssemblyName>
    <RootNamespace>HybridCLR.Lab.ReferenceRunner</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../managed-cases/HybridCLR.ManagedCases/HybridCLR.ManagedCases.csproj" />
  </ItemGroup>
</Project>

