[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("Prepare", "Player")]
    [string]$Action,
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath,
    [Parameter(Mandatory = $true)]
    [string]$SettingsFile,
    [Parameter(Mandatory = $true)]
    [string]$RuntimeSource,
    [Parameter(Mandatory = $true)]
    [string]$OutputRoot,
    [Parameter(Mandatory = $true)]
    [string]$Target,
    [Parameter(Mandatory = $true)]
    [ValidateRange(1, 1)]
    [int]$ToolchainContractVersion,
    [Parameter(Mandatory = $true)]
    [ValidateSet("Release", "Exploratory")]
    [string]$Mode,
    [string]$BaselineAotRoot = "",
    [string]$BaselineManifestPath = "",
    [string]$AdapterOptionsPath = "",
    [string]$ProjectPlan = "",
    [string]$ProjectPlanValidation = "",
    [string]$BatchReport = "",
    [string]$SourcePreflight = "",
    [string]$CleanCheckoutGate = "",
    [switch]$RequireCompleteCoverage,
    # Optional project-owned device runner for Android/iOS (or a replacement
    # for the default Windows process runner). The runner must write a passing
    # dhe-player-result.json to -ResultPath and exit zero.
    [string]$PlayerSmokeRunner = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Generated by HybridCLR DHE toolchain __DHE_TOOLCHAIN_VERSION__.
# Implement project-specific Unity/IL2CPP integration only in this adapter.
if ($Action -eq "Prepare") {
    # Build the exact stripped-AOT baseline and current hot-update assembly
    # roots, then write <OutputRoot>/adapter/prepare.json using
    # schemas/dhe-project-adapter-prepare.schema.json. The report must echo
    # toolchainContractVersion so incompatible adapters fail before preflight.
    throw "Implement the DHE adapter Prepare action for target '$Target' (baseline root: '$BaselineAotRoot')."
}

foreach ($requiredPath in @($ProjectPlan, $ProjectPlanValidation, $BatchReport, $SourcePreflight, $CleanCheckoutGate)) {
    if ([string]::IsNullOrWhiteSpace($requiredPath) -or -not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
        throw "DHE adapter Player received an incomplete validated input set."
    }
}

# Build and run the target Player from the validated plan, then write the
# standard <OutputRoot>/workflow-report.json.
throw "Implement the DHE adapter Player action for target '$Target'."
