<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Unity/**/*.cs" />
    <Compile Include="../../MetaVersion.cs" Link="MetaVersion.cs" />
    <Compile Include="../../ResourceUpdateCompatibility.cs" Link="ResourceUpdateCompatibility.cs" />
    <Compile Include="../../DheValueLayoutImpact.cs" Link="DheValueLayoutImpact.cs" />
    <Compile Include="../../ResourceExecutionPlan.cs" Link="ResourceExecutionPlan.cs" />
    <Reference Include="dnlib"><HintPath>../../dnlib.dll</HintPath></Reference>
  </ItemGroup>
</Project>
