<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>HybridCLR.CrossAssemblyDerived</AssemblyName>
    <RootNamespace>HybridCLR.Lab.CrossAssemblyDerived</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HybridCLR.ManagedCases/HybridCLR.ManagedCases.csproj" />
  </ItemGroup>
</Project>
