<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DheUnityPackageRoot Condition="'$(DheUnityPackageRoot)' == ''">$(MSBuildThisFileDirectory)../../../unity2021-dhe-demo/Packages/com.code-philosophy.hybridclr</DheUnityPackageRoot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(DheUnityPackageRoot)/Editor/Link/DheLinkerPreservation.cs" Link="DheLinkerPreservation.cs" />
    <Reference Include="dnlib"><HintPath>../../dnlib.dll</HintPath></Reference>
  </ItemGroup>
</Project>
